### PR TITLE
fix(classAces): fixing broken Class permission granting.

### PR DESCRIPTION
**Pull request by cobrowserAlex**
* specialized the findOrCreateAcl for Classes because it has to look for or create an Oid for a class not an instance with an Id
* added posibility to supply an ObjectIdentity to grant so that you don't need an instantiated document to create a Class based permisson

### CODE REVIEW

**Comment by cobrowserAlex** [comment]
I'll reopen after all tests are fixed...

**Comment by cobrowserAlex** [comment]
This consists fix and a new feature when using this bundle with https://github.com/zerodine/MongoDBAclBundle and granting a Class permission.
I don't know if this happens in other db's too, but an oid for a class acl was never made. It made a record for the instance.

I also added a feature that allows you to create an class ACE without actually having an instance of a class. This is useful for allowing CREATE persmission of the **first** instance.

please let me know your thoughts.

Alex

**Comment by danez** [comment]
Thanks for the contribution. I will have a look asap.

**Comment by cobrowserAlex** [comment]
@danez i removed some cruft, are you able to merge?

**Comment by danez** [comment]
I refactored it all a little bit and fixed all the stuff you mentioned. I will update the docs and then release a new version. sorry for the long delay.

Maybe you can check if it now works for you. At least all the tests now work with ORM. Need to also add tests for ODM.

**Comment by cobrowserAlex** [comment]
Hi @danez thanks for that, it's working great!

**Pull request closed without merging**
